version: 5.0.0.{build}

# cache:
#  - "%LOCALAPPDATA%\\Yarn"

skip_tags: true

branches:
  only:
    - master

install:
  - ps: Install-Product node 8
  #- ps: Update-NodeJsInstallation 7.10.1 x86
  - cmd: set PATH=node_modules\.bin;%cd%\node_modules\.bin;%PATH%
  - npm cache verify
  - _hansen_install_electron
  - npm install -g gulp
  # regular npm install from _hansen_install_electron removes gulp??? maybe it's the arch???
  - npm install gulpjs/gulp#4.0 https://github.com/meetfranz/node-auto-launch.git

before_build:
  - yarn lint
  - gulp -v

build_script:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  - gulp build
  - node_modules\.bin\electron-builder --publish onTag --ia32

notifications:
  - provider: Slack
    incoming_webhook:
      secure: /tQzfO0uCSjCMZF2eqIdIGAxeA/Zyn2eKDJKfcnvwV4qHnT8wXhKj6rS4Mm5MTkjmIMt4JBPdQIbyviBwfXvLt0cGFParmWyOuStdSRGVzEN6mZF8Hg+4QuWXMJ25vBxipZTnWUvtdwIPyE6JNStSCR/llRE70EmtOJCmA/T+HqzIpLXCD8FiP/Aq5rI8GCM

artifacts:
  - path: out\*.exe
  - path: out\*.yml
    name: Version Info
  - path: out\win-ia32-unpacked
    name: Portable Build
    type: zip
    
deploy:
    # deploying to GitHub releases
  - provider: GitHub
    tag: uwx-franz-$(APPVEYOR_BUILD_NUMBER)
    release: "uwx's personalized Franz build r$(APPVEYOR_BUILD_NUMBER)"
    description: |
      Build project $(APPVEYOR_PROJECT_ID)
      Cloned repo to $(APPVEYOR_BUILD_FOLDER)
      Revision $(APPVEYOR_BUILD_NUMBER) ($(APPVEYOR_REPO_SCM) commit $(APPVEYOR_REPO_COMMIT) from $(APPVEYOR_REPO_NAME)/$(APPVEYOR_REPO_BRANCH))
      Commit info:
      ```
      $(APPVEYOR_REPO_COMMIT_TIMESTAMP) $(APPVEYOR_REPO_COMMIT_AUTHOR):
      $(APPVEYOR_REPO_COMMIT_MESSAGE)
      ```
    auth_token:
      secure: P6fLO7WZwzqHvmMFHtii8ToXcxF25nJnh/GThOE7hSb4TEs+h3ARPzKXVCcHSf/P # your encrypted token from GitHub
    artifact: /.*\.(exe|zip)/
    draft: false
    prerelease: true
    on:
      branch: master                 # release from master branch only
      appveyor_repo_tag: false       # no deploy on tag push
      
