version: 5.0.0.{build}

# cache:
#  - "%LOCALAPPDATA%\\Yarn"

skip_tags: true

branches:
  only:
    - master

cache:
  - node_modules -> package.json
  - '%LOCALAPPDATA%/Yarn -> package.json'
  - '%APPDATA%\npm-cache -> package.json'
  - yarn.lock -> package.json
  - package-lock.json -> package.json

install:
  - ps: Install-Product node 8
  - yarn cache clean
  - _hansen_install_electron
  - >-
      yarn global add babel-eslint babel-plugin-transform-class-properties babel-plugin-transform-decorators-legacy
      babel-plugin-transform-flow-strip-types babel-preset-env babel-preset-es2015 babel-preset-es2016
      babel-preset-es2017 babel-preset-react babel-preset-stage-0 babel-preset-stage-1 eslint eslint-config-airbnb
      eslint-loader eslint-plugin-import eslint-plugin-jsx-a11y eslint-plugin-react gulp gulp-babel gulp-github-release
      gulp-sass gulp-sass-variables gulp-server-livereload

before_build:
  - yarn lint

build_script:
  - yarn build

notifications:
  - provider: Slack
    incoming_webhook:
      secure: /tQzfO0uCSjCMZF2eqIdIGAxeA/Zyn2eKDJKfcnvwV4qHnT8wXhKj6rS4Mm5MTkjmIMt4JBPdQIbyviBwfXvLt0cGFParmWyOuStdSRGVzEN6mZF8Hg+4QuWXMJ25vBxipZTnWUvtdwIPyE6JNStSCR/llRE70EmtOJCmA/T+HqzIpLXCD8FiP/Aq5rI8GCM

artifacts:
  - path: out\*.exe
  - path: out\*.yml
    name: Version Info
  - path: out\win-ia32-unpacked
    name: Portable Build
    type: zip
    
deploy:
    # deploying to GitHub releases
  - provider: GitHub
    tag: uwx-franz-$(APPVEYOR_BUILD_NUMBER)
    release: "uwx's personalized Franz build r$(APPVEYOR_BUILD_NUMBER)"
    description: |
      Build project $(APPVEYOR_PROJECT_ID)
      Cloned repo to $(APPVEYOR_BUILD_FOLDER)
      Revision $(APPVEYOR_BUILD_NUMBER) ($(APPVEYOR_REPO_SCM) commit $(APPVEYOR_REPO_COMMIT) from $(APPVEYOR_REPO_NAME)/$(APPVEYOR_REPO_BRANCH))
      Commit info:
      ```
      $(APPVEYOR_REPO_COMMIT_TIMESTAMP) $(APPVEYOR_REPO_COMMIT_AUTHOR):
      $(APPVEYOR_REPO_COMMIT_MESSAGE)
      ```
    auth_token:
      secure: P6fLO7WZwzqHvmMFHtii8ToXcxF25nJnh/GThOE7hSb4TEs+h3ARPzKXVCcHSf/P # your encrypted token from GitHub
    artifact: /.*\.(exe|zip)/
    draft: false
    prerelease: true
    on:
      branch: master                 # release from master branch only
      appveyor_repo_tag: false       # no deploy on tag push
      
